name: palletization-dual-ur10e
services:
  Robot_1_UR10e:
    container_name: robot_1_ur10e
    image: universalrobots/ursim_e-series:latest
    ports:
      - 5901:5900 # VNC port: 5900
      - 6081:6080 # Web browser VNC port: 6080
      - 29991:29999 # Dashboard port: 29999
      - 30011-30014:30001-30004 # Real-time client ports: 30001-30004
    stdin_open: true
    tty: true
    environment:
      - ROBOT_MODEL=UR10
    volumes:
      - ./ursim/programs_1:/ursim/programs
  
  Robot_2_UR10e:
    container_name: robot_2_ur10e
    image: universalrobots/ursim_e-series:latest
    ports:
      - 5902:5900 # VNC port: 5900
      - 6082:6080 # Web browser VNC port: 6080
      - 29992:29999 # Dashboard port: 29999
      - 30021-30024:30001-30004 # Real-time client ports: 30001-30004
    stdin_open: true
    tty: true
    environment:
      - ROBOT_MODEL=UR10
    volumes:
      - ./ursim/programs_2:/ursim/programs